detector:
  config_file_path: 'assets/cow_detector_faster_rcnn_mobile.yml'
  rpn_model_path: 'assets/mobile_1.0_faster_rcnn_rpn.pb'
  rcnn_model_path: 'assets/mobile_1.0_faster_rcnn_rcnn.pb'
  classes:
  - 'background'
  - 'head'
  net: 'mobile'


reognizer:
  model_path: 'assets/cow_recognizer_947.pb'
  image_size: 182