detector:
  config_file_path: 'assets/cow_detector_faster_rcnn.yml'
  rpn_model_path: 'assets/res50_faster_rcnn_rpn.pb'
  rcnn_model_path: 'assets/res50_faster_rcnn_rcnn.pb'
  classes:
  - 'background'
  - 'head'
  net: 'res50'

reognizer:
  model_path: 'assets/cow_recognizer_4065.pb'
  image_size: 182
  compare_threshold: 0.99

face_aligner:
  model_path: 'assets/cow_face_landmarks.pb'