ANCHOR_RATIOS: [0.1,0.2,0.3]
ANCHOR_SCALES: [2,3]
FEAT_STRIDE: [16]
TEST:
  HAS_RPN: True
  RPN_POST_NMS_TOP_N: 16
  RPN_PRE_NMS_TOP_N: 400
  RPN_NMS_THRESH: 0.5
  MAX_SIZE: 310
MOBILENET:
  DEPTH_MULTIPLIER: 0.25
POOLING_MODE: crop
USE_GPU_NMS: False